baseURL = "https://CLIVERCHEN.github.io/"
languageCode = "en-us"
title = "Keru Chen"
theme = "barks"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

[params.author]
name = "Keru Chen"
headline = "PhD Student - ASU ECEE"
bio = "First-year PhD student in Electrical, Computer, and Energy Engineering at Arizona State University, advised by Shaofeng Zou. My research interests include reinforcement learning, large language models, and AI for healthcare. I received my B.Eng. in Automation from Xi'an Jiaotong University."

[[params.social]]
name = "Email"
url = "mailto:kchen234@asu.edu"

[[params.social]]
name = "GitHub"
url = "https://github.com/CLIVERCHEN"

[[params.social]]
name = "Advisor"
url = "https://sites.google.com/view/szou/home?authuser=0"

[menu]

[[menu.main]]
name = "Research"
url = "/research/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5
