baseURL = "https://CLIVERCHEN.github.io/"
languageCode = "en-us"
title = "Keru Chen"
theme = "barks"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

# ---------------- Social links (footer icons) ----------------

[[params.social]]
name = "Email"
url = "mailto:kchen234@asu.edu"

[[params.social]]
name = "GitHub"
url = "https://github.com/CLIVERCHEN"

[[params.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=W0LexmIAAAAJ&hl=en"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/keru-chen-23ba0128a/"


[menu]

[[menu.main]]
name = "Research"
url = "/research/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5
